@baseUrl = http://localhost:3001

### Blogs
###
GET {{baseUrl}}/api/blogs

###
POST {{baseUrl}}/api/blogs
Content-Type: application/json

{
    "title":"The race to extinction",
    "author":"Elon Musk",
    "url":"https://tesla.com",
    "likes":33
}

### Users
###
GET {{baseUrl}}/api/users

###
POST {{baseUrl}}/api/users
Content-Type: application/json

{
    "username": "hegde",
    "password": "top sekret",
    "name": "Bindu Hegde"
}

###
POST {{baseUrl}}/api/users
Content-Type: application/json

{
    "username": "dharma",
    "password": "sekret",
    "name": "Dharma Teja Nuli"
}

### Login
###
POST {{baseUrl}}/api/login
Content-Type: application/json

{
    "username": "dharma",
    "password": "secret"
}